### ISSUE TITLE
Add scrolling capability to MultiSelect component

### ISSUE THREAD

**Issue by jblotus** [wxsms/uiv#212]
The MultiSelect is great, but for very long lists it ends up being very awkward and too long for the screen. Would it be possible to add a scroll functionality at a certain height?

I found an example of how this could be achieved:

https://bootsnipp.com/snippets/MaKa3

I'll see if I can hack something together if this feature would be useful to the project.

**Comment by wxsms** [comment]
In your example, the scrolling feature is bring by CSS:

```css
.scrollable-menu {
    height: auto;
    max-height: 200px;
    overflow-x: hidden;
}
```

you can do the same in this project.
