### ISSUE TITLE
Question: what is the best way to make an Alert use a fade transition for showing/hiding with v-if?

### ISSUE THREAD

**Issue by u01jmg3** [wxsms/uiv#215]
- What is the best way to make an Alert use a fade transition for showing/hiding with `v-if`?

```css
.fade-enter,
.fade-leave {
    height: 0;
    opacity: 0;
}

.fade-transition {
    transition: opacity .3s ease;
}
```
